### ISSUE TITLE
Composer.json tells composer this package provides "psr/http-factory"

### ISSUE THREAD

**Issue by groot406** [tuupola/http-factory#18]
Composer 2 now doesn't install the required "psr/http-factory" package.

This package should however provide an implementation for "psr/http-factory"

**Comment by tuupola** [comment]
This was fixed in [1.0.2](https://github.com/tuupola/http-factory/blob/master/CHANGELOG.md#102---2018-12-22). If you encounter the above problem with Composer 2 bump the minimum requirement to `^1.0.2`. Ie. `composer.json` should have:

```
"tuupola/http-factory": "^1.0.2"
```

**Comment by groot406** [comment]
Fixed in 1.0.2
