### ISSUE TITLE
Add support for Slim\Psr7\Request and Slim\Psr7\Response (Slim 4.0.0 Beta)

### ISSUE THREAD

**Issue by wernerm** [tuupola/http-factory#9]
The current class detection implementation does not work with Slim 4.0.0 Beta.

Detection needs to be added for `Slim\Psr7\Response` (Slim 4) in addition to the current `Slim\Http\Response` (Slim 3).

Adding additional support for `Slim\Psr7\Request` and `Slim\Psr7\Response` would enable other libraries, like [tuupola/slim-basic-auth](https://github.com/tuupola/slim-basic-auth) to work with Slim 4.0.0 Beta while maintaining backward compatibility with Slim 3.

**Comment by dakujem** [comment]
Stumbled upon this too.

**Comment by dakujem** [comment]
@wernerm Solved in `v1.1`.
